image:
  repository: junseokoo/blog.be
  tag: build-67
  pullPolicy: IfNotPresent

nodeSelector:
  kubernetes.io/hostname: worker-node10

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  
serviceAccount:
  create: true
  name: "blog-service-account"

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls:
    - secretName: blog-tls
      hosts:
        - "blog.example.com"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80